/* This file is automatically generated from reds/red_command.h */

#pragma once

#ifndef __MOTR_REDS_RED_COMMAND_XC_H__
#define __MOTR_REDS_RED_COMMAND_XC_H__

#ifndef __KERNEL__
#include <sys/types.h>
#endif

#include "xcode/xcode.h"

extern struct m0_xcode_type *m0_red_command_req_xc;
extern struct m0_xcode_type *m0_red_command_rep_xc;

M0_INTERNAL void m0_xc_m0_red_command_req_struct_init(void);
M0_INTERNAL void m0_xc_m0_red_command_rep_struct_init(void);


M0_INTERNAL void m0_xc_reds_red_command_init(void);
M0_INTERNAL void m0_xc_reds_red_command_fini(void);

/* __MOTR_REDS_RED_COMMAND_XC_H__ */
#endif

