/* This file is automatically generated from reds/red_command.h */

#include "lib/misc.h"                       /* offsetof */
#include "lib/assert.h"
#include "xcode/xcode.h"

#include "reds/red_command.h"
#include "reds/red_command_xc.h"

struct m0_xcode_type *m0_red_command_req_xc;
struct m0_xcode_type *m0_red_command_rep_xc;

static struct _m0_red_command_req_s {
	struct m0_xcode_type  _type;
	struct m0_xcode_field _child[3];
} _m0_red_command_req = {
	._type = {
		.xct_aggr   = M0_XA_RECORD,
		.xct_name   = "m0_red_command_req",
		.xct_sizeof = sizeof (struct m0_red_command_req),
		.xct_nr     = 3,
		.xct_flags  = M0_XCODE_TYPE_FLAG_DOM_RPC,
	}
};

struct m0_xcode_type *m0_red_command_req_xc = &_m0_red_command_req._type;
M0_BASSERT(offsetof(struct _m0_red_command_req_s, _child[0]) ==
	offsetof(struct m0_xcode_type, xct_child[0]));

static struct _m0_red_command_rep_s {
	struct m0_xcode_type  _type;
	struct m0_xcode_field _child[2];
} _m0_red_command_rep = {
	._type = {
		.xct_aggr   = M0_XA_RECORD,
		.xct_name   = "m0_red_command_rep",
		.xct_sizeof = sizeof (struct m0_red_command_rep),
		.xct_nr     = 2,
		.xct_flags  = M0_XCODE_TYPE_FLAG_DOM_RPC,
	}
};

struct m0_xcode_type *m0_red_command_rep_xc = &_m0_red_command_rep._type;
M0_BASSERT(offsetof(struct _m0_red_command_rep_s, _child[0]) ==
	offsetof(struct m0_xcode_type, xct_child[0]));


M0_BASSERT(sizeof(struct m0_red_command_req) == 12U);

M0_BASSERT(sizeof ((struct m0_red_command_req *)0)->fcr_disp == 1U);
M0_BASSERT(offsetof(struct m0_red_command_req, fcr_disp) == 0U);
M0_BASSERT(sizeof ((struct m0_red_command_req *)0)->fcr_num1 == 4U);
M0_BASSERT(offsetof(struct m0_red_command_req, fcr_num1) == 4U);
M0_BASSERT(sizeof ((struct m0_red_command_req *)0)->fcr_num2 == 4U);
M0_BASSERT(offsetof(struct m0_red_command_req, fcr_num2) == 8U);

M0_BASSERT(sizeof(struct m0_red_command_rep) == 8U);

M0_BASSERT(sizeof ((struct m0_red_command_rep *)0)->fcp_rc == 4U);
M0_BASSERT(offsetof(struct m0_red_command_rep, fcp_rc) == 0U);
M0_BASSERT(sizeof ((struct m0_red_command_rep *)0)->fcp_result == 4U);
M0_BASSERT(offsetof(struct m0_red_command_rep, fcp_result) == 4U);



M0_INTERNAL void m0_xc_m0_red_command_req_struct_init(void)
{
	_m0_red_command_req._child[0] = (struct m0_xcode_field) {
		.xf_name   = "fcr_disp",

		.xf_type   = &M0_XT_U8,

		.xf_tag    = 0,
		.xf_opaque = NULL,
		.xf_offset = offsetof(struct m0_red_command_req, fcr_disp),
		.xf_read   = NULL,
		.xf_decor  = {
			[M0_XCODE_DECOR_READ] = NULL
		}
	};
	m0_xc_u8_init();

	_m0_red_command_req._child[1] = (struct m0_xcode_field) {
		.xf_name   = "fcr_num1",

		.xf_type   = &M0_XT_U32,

		.xf_tag    = 0,
		.xf_opaque = NULL,
		.xf_offset = offsetof(struct m0_red_command_req, fcr_num1),
		.xf_read   = NULL,
		.xf_decor  = {
			[M0_XCODE_DECOR_READ] = NULL
		}
	};
	m0_xc_u32_init();

	_m0_red_command_req._child[2] = (struct m0_xcode_field) {
		.xf_name   = "fcr_num2",

		.xf_type   = &M0_XT_U32,

		.xf_tag    = 0,
		.xf_opaque = NULL,
		.xf_offset = offsetof(struct m0_red_command_req, fcr_num2),
		.xf_read   = NULL,
		.xf_decor  = {
			[M0_XCODE_DECOR_READ] = NULL
		}
	};
	m0_xc_u32_init();

	M0_POST(m0_xcode_type_invariant(m0_red_command_req_xc));
}

M0_INTERNAL void m0_xc_m0_red_command_rep_struct_init(void)
{
	_m0_red_command_rep._child[0] = (struct m0_xcode_field) {
		.xf_name   = "fcp_rc",

		.xf_type   = &M0_XT_U32,

		.xf_tag    = 0,
		.xf_opaque = NULL,
		.xf_offset = offsetof(struct m0_red_command_rep, fcp_rc),
		.xf_read   = NULL,
		.xf_decor  = {
			[M0_XCODE_DECOR_READ] = NULL
		}
	};
	m0_xc_u32_init();

	_m0_red_command_rep._child[1] = (struct m0_xcode_field) {
		.xf_name   = "fcp_result",

		.xf_type   = &M0_XT_U32,

		.xf_tag    = 0,
		.xf_opaque = NULL,
		.xf_offset = offsetof(struct m0_red_command_rep, fcp_result),
		.xf_read   = NULL,
		.xf_decor  = {
			[M0_XCODE_DECOR_READ] = NULL
		}
	};
	m0_xc_u32_init();

	M0_POST(m0_xcode_type_invariant(m0_red_command_rep_xc));
}

M0_INTERNAL void m0_xc_reds_red_command_init(void)
{
	m0_xc_m0_red_command_req_struct_init();
	m0_xc_m0_red_command_rep_struct_init();
}

M0_INTERNAL void m0_xc_reds_red_command_fini(void)
{
}
